name: Upload AllowList to Nitrado

on:
  push:
    paths:
      - "Testmap/Testmap"

jobs:
  upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Rename your file to AllowList.cfg
        run: |
          cp Testmap/Testmap AllowList.cfg

      - name: Upload AllowList.cfg to Nitrado FTP
        uses: sebastianpopp/ftp-action@v2
        with:
          host: ${{ secrets.FTP_HOST }}
          user: ${{ secrets.FTP_USER }}
          password: ${{ secrets.FTP_PASS }}
          localDir: "."
          remoteDir: ${{ secrets.FTP_PATH }}
          forceSsl: true
